# Generated by Django 5.2.8 on 2025-11-08 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_owner', models.CharField(max_length=255)),
                ('repo_name', models.CharField(max_length=255)),
                ('github_repo_id', models.BigIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_repos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('repo_owner', 'repo_name')},
            },
        ),
        migrations.CreateModel(
            name='PullRequestScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_number', models.IntegerField()),
                ('pr_title', models.CharField(max_length=500)),
                ('pr_branch', models.CharField(max_length=255)),
                ('pr_sha', models.CharField(max_length=40)),
                ('preview_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('waiting_preview', 'Waiting for Preview'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('gobuster_results', models.JSONField(blank=True, null=True)),
                ('vulnar_results', models.JSONField(blank=True, null=True)),
                ('nikto_results', models.JSONField(blank=True, null=True)),
                ('sqlmap_results', models.JSONField(blank=True, null=True)),
                ('total_findings', models.IntegerField(default=0)),
                ('critical_findings', models.IntegerField(default=0)),
                ('github_comment_id', models.BigIntegerField(blank=True, null=True)),
                ('github_check_run_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pr_scans', to='github_integration.monitoredrepository')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('repository', 'pr_number', 'pr_sha')},
            },
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='github_integration.pullrequestscan')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
