# Generated by Django 5.2.8 on 2025-11-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredrepository',
            name='installation_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
